// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKQyFr0JZerDgLfKjpJnGy4LUiPHqicc',
    appId: '1:706415367275:web:d686657f490f231e1c4d2e',
    messagingSenderId: '706415367275',
    projectId: 'testapp-c1bce',
    authDomain: 'testapp-c1bce.firebaseapp.com',
    storageBucket: 'testapp-c1bce.appspot.com',
    measurementId: 'G-BDNT5PW04H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYymGzSgoASWO81AAbVVzGeWOaTM-jB_w',
    appId: '1:706415367275:android:2646860067d354471c4d2e',
    messagingSenderId: '706415367275',
    projectId: 'testapp-c1bce',
    storageBucket: 'testapp-c1bce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmQ_QldSM8nCPNAUcJlrhBRo82Sb_f4Eo',
    appId: '1:706415367275:ios:82c01376e146ac811c4d2e',
    messagingSenderId: '706415367275',
    projectId: 'testapp-c1bce',
    storageBucket: 'testapp-c1bce.appspot.com',
    iosClientId: '706415367275-cm9hg8b54912sbuki0lqlbph7dr3uci0.apps.googleusercontent.com',
    iosBundleId: 'com.example.registrationForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmQ_QldSM8nCPNAUcJlrhBRo82Sb_f4Eo',
    appId: '1:706415367275:ios:4dd5bb24c3049f4a1c4d2e',
    messagingSenderId: '706415367275',
    projectId: 'testapp-c1bce',
    storageBucket: 'testapp-c1bce.appspot.com',
    iosClientId: '706415367275-l9ddqj6oa2pacog4fgm1vtvket885o89.apps.googleusercontent.com',
    iosBundleId: 'com.example.registrationForm.RunnerTests',
  );
}
